<a href="https://colab.research.google.com/github/shahdelmasry12/AI-and-ML-labs/blob/main/Pandas%2BPractice_checkpoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [4]:
#Write your code here
# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import pandas
import pandas as pd
import numpy as np
file_path = '/content/drive/MyDrive/iti_data_csv/Purchase_Data.csv'
df_data= pd.read_csv(file_path)
print("CSV file loaded successfully! Here are the first few rows:")
print(df_data.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CSV file loaded successfully! Here are the first few rows:
   invoice_number   invoice_time store_id  product_id  category_id  num_item  \
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101       1.0
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203       1.0
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203       1.0
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401       1.0
4    2.020000e+11  7/15/15 12:16     G816     7090363        70401       1.0

   price
0    2.0
1    2.0
2    2.0
3    6.0
4    6.0

Use the dtypes attribute to view how each column is stored

In [5]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [6]:
#Write you code here
result_1= df_data.loc[:, 'invoice_number':'invoice_time']
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [9]:
#Write you code here
result_2= df_data.loc[0:1, :]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [12]:
#Write your code here
result_3=df_data.iloc[:4,:5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [13]:
#Write your code here
result_4=df_data.loc[[0,4,6],['invoice_time','price']]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [17]:
num_rows=df_data.shape[0]
num_columns=df_data.shape[1]
print(f"The number of rows= {num_rows}")
print(f"The number of columns = {num_columns}")

The number of rows= 5382
The number of rows= 7

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [18]:
#Write your code here
num_rows=df_data.shape[0]
last_row=df_data.iloc[num_rows-1,:]
print(last_row)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [23]:
#Write your code here
avg_price=df_data['price'].mean()
max_price=df_data['price'].max()
print(f"The average price is {avg_price:.2f}")
print(f"The maximum price is {max_price}")

The average price is 3.19
The maximum price is 6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [24]:
#Write you code here
avg_price,avg_num_items=df_data[['price','num_item']].mean()
print(f"The average price is {avg_price:.2f}")
print(f"The average number of items is {avg_num_items:.2f}")

The average price is 3.19
The average number of items is 1.30

Create a column called "total", which is the product of the price and num_item columns.

In [27]:
#Write your code here
df_data['total']=df_data['price']*df_data['num_item']
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0
...,...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0,4.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0,2.0

What is the avgerage price of the three most expensive purchases?

In [29]:
#Write your code here
max_price=df_data['price'].nlargest(3)
avg_price=max_price.mean()
print(f"The average price of the three most expensive purchases is {avg_price:.2f}")

The average price of the three most expensive purchases is 6.00

How many different products are there?

In [31]:
#Write your code here
different_products=df_data['product_id'].nunique()
print(f"There are {different_products} different products")

There are 53 different products

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [32]:
#Write your code here
diff_min_med=df_data['total'].describe()['mean']-df_data['total'].describe()['50%']
print(f"The difference between the mean and median of the column total is {diff_min_med:.2f}")

The difference between the mean and median of the column total is 0.93

Use the drop() method to delete the column total from the dataframe df_data.

In [33]:
#Write your code here
df_data.drop(columns=['total'],inplace=True)
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

In [36]:
#Write your code here
df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])
print("num of rows and columns= ",df_data.shape)   # عدد الصفوف والأعمدة
print()
print(f"Data types in each column {df_data.dtypes}")  # أنواع البيانات في كل عمود
print()
print(f" {df_data.describe()}")#معلومات احصائيه
print()
df_data.isnull().sum() #مجموع القيم الناقصه

invoice_number    0
invoice_time      0
store_id          0
product_id        0
category_id       0
num_item          0
price             0
dtype: int64

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [38]:
#Write your code here
df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])
print(f"Data types in each column \n{df_data.dtypes}")

Data types in each column
invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [39]:
#Write your code here
df_data['DOW'] = df_data['invoice_time'].dt.day_name()
df_data['Month'] = df_data['invoice_time'].dt.month
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [40]:
#Write your code here
num_purchases_wed=df_data['DOW'].value_counts()['Wednesday']
print(f"The number of purchases made on Wednesday is {num_purchases_wed}")

The number of purchases made on Wednesday is 959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [45]:
#Write your code here
file_path = '/content/drive/MyDrive/iti_data_csv/Titanic.csv'
df_titanic= pd.read_csv(file_path)
print("CSV file loaded successfully! Here are the first few rows:")
print(df_titanic.head())

CSV file loaded successfully! Here are the first few rows:
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [46]:
#Write your code here
df_titanic.rename(columns={'Name':'Passenger_Name','Ticket':'Ticket_Num'},inplace=True)
df_titanic

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Change the index of the df_titanic to the column PasengerID.

In [47]:
#Write your code here
df_titanic.set_index('PassengerId',inplace=True)
df_titanic

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

Select the name of passenger 896

In [48]:
#Write your code here
df_titanic.loc[896,'Passenger_Name']

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [49]:
#Write your code here
df_titanic.reset_index(inplace=True)
df_titanic

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [53]:
#Write you code here
missing_age_count = df_titanic['Age'].isnull().sum()
print(f"The number of missing entries in the Age column is: {missing_age_count}")

The number of missing entries in the Age column is: 86

Compute the avg age of passengers ignoring the missing data.

In [56]:
#Write your code here
avg_age=df_titanic['Age'].mean()
print(f"The average age of passengers is {avg_age:.2f}")

The average age of passengers is 30.27

Using the fillna() method replace the missing values in the Age column with the mean.

In [59]:
#Write your code here
df_titanic['Age'].fillna(avg_age,inplace=True)
missing_age_count = df_titanic['Age'].isnull().sum()
print(f"The number of missing entries in the Age column is: {missing_age_count}")

The number of missing entries in the Age column is: 0

/tmp/ipython-input-3938809536.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_titanic['Age'].fillna(avg_age,inplace=True)

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [60]:
#Write your code here
avg_age_5_oldest=df_titanic.nlargest(5,'Age')['Age'].mean()
print(f"The average age of the 5 oldest passengers is {avg_age_5_oldest:.2f}")

The average age of the 5 oldest passengers is 67.00